name       : ROCR
version    : 2.7.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/ROCR-Runtime/archive/roc-2.7.0.tar.gz : 726b6556d4072caa35e751e067f4e5dd283583ed0aff49d72af14e0449bfe318
license    : NCSA
component  : programming.devel
summary    : This repository includes the user-mode API interfaces and libraries necessary for host applications to launch compute kernels to available HSA ROCm kernel agents.
description: |
    This repository includes the user-mode API interfaces and libraries necessary for host applications to launch compute kernels to available HSA ROCm kernel agents.
builddeps  :
    - pkgconfig(libelf)
    - ROCT
    - ROCT-devel
setup      : |
    cd src
    mkdir -p build
    cd build
    %cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=. 
build      : |
    cd src/build
    %make
install    : |
    cd src/build
    install -D -m 00644 libhsa-runtime64.so.1.1.9 $installdir/%libdir%/libhsa-runtime64.so.1.1.9
    ln -sv libhsa-runtime64.so.1.1.9 $installdir/%libdir%/libhsa-runtime64.so.1
    ln -sv libhsa-runtime64.so.1 $installdir/%libdir%/libhsa-runtime64.so
    #echo '/usr/lib64/rocm/hsa/lib' > hsa-rocr-dev.conf
    #install -Dm00644 hsa-rocr-dev.conf $installdir/usr/share/ld.so.conf.d/hsa-rocr-dev.conf
    
    cd ../inc
    install -D -m 00644 amd_hsa_common.h $installdir/usr/include/hsa/amd_hsa_common.h
    install -D -m 00644 amd_hsa_elf.h $installdir/usr/include/hsa/amd_hsa_elf.h
    install -D -m 00644 amd_hsa_kernel_code.h $installdir/usr/include/hsa/amd_hsa_kernel_code.h
    install -D -m 00644 amd_hsa_queue.h $installdir/usr/include/hsa/amd_hsa_queue.h
    install -D -m 00644 amd_hsa_signal.h $installdir/usr/include/hsa/amd_hsa_signal.h
    install -D -m 00644 Brig.h $installdir/usr/include/hsa/Brig.h
    install -D -m 00644 hsa_api_trace.h $installdir/usr/include/hsa/hsa_api_trace.h
    install -D -m 00644 hsa_ext_amd.h $installdir/usr/include/hsa/hsa_ext_amd.h
    install -D -m 00644 hsa_ext_finalize.h $installdir/usr/include/hsa/hsa_ext_finalize.h
    install -D -m 00644 hsa_ext_image.h $installdir/usr/include/hsa/hsa_ext_image.h
    install -D -m 00644 hsa.h $installdir/usr/include/hsa/hsa.h
    install -D -m 00644 hsa_ven_amd_aqlprofile.h $installdir/usr/include/hsa/hsa_ven_amd_aqlprofile.h
    install -D -m 00644 hsa_ven_amd_loader.h $installdir/usr/include/hsa/hsa_ven_amd_loader.h



    




    
